### ISSUE TITLE
파이어폭스 부가기능에도 추가해주세요

### ISSUE THREAD

**Issue by nyankase** [WooyeongCho/Pyer#1]
파이어폭스로 부가기능 추가하면 *background.presistent*에 에러가 났답니다.
아무래도 *background.js*에 크롬만 지원하는 기능이 있어서 그런가 본데 좀 고쳐서 파이어폭스 부가기능에도 추가해주세요.

**Comment by WooyeongCho** [comment]
의견 감사합니다. 파이어폭스에서 사용 가능한 Pyer를 아직 개발할 계획은 없지만, 추후에 가능하다면 파이어폭스용 Pyer를 개발하겠습니다.
